### ISSUE TITLE
promise question

### ISSUE THREAD

**Issue by sishen654** [3imed-jaberi/koa-mongo-sanitize#1]
Because the function have not to use async await support, focus before async function can't normally trigger.
It must to await the next function.

**Comment by sishen654** [comment]
I can just use this way to compatible code.
```js
import { sanitize } from "koa-mongo-sanitize"

app.use(async (ctx, next) => {  
  sanitize()
  await next();
});
```

**Comment by 3imed-jaberi** [comment]
@sishen654, thank you for your report! when I made this module I didn't make a full app or deep integration test to check the up/down middleware traffic, so yeah you're right.

It will be fixed in the next release `1.1.0`!

**Comment by 3imed-jaberi** [comment]
@sishen654, [the next release is here](https://www.npmjs.com/package/koa-mongo-sanitize) 🎉!

**Comment by sishen654** [comment]
> @sishen654, [the next release is here](https://www.npmjs.com/package/koa-mongo-sanitize) 🎉!

cool! Really fast.
